### ISSUE TITLE
SMS restore broken (MySQL Syntax error or access violation)

### ISSUE THREAD

**Issue by michiil** [nerzhul/ocsms#140]
### Steps to reproduce
1. Start SMS restore on Android App

### Expected behaviour
SMS get restrored

### Actual behaviour
SMS don't get restored

### Server configuration

**ownCloud version:** Nextcloud 10.0.2 

**PHP version:** 7.0.8

**HTTPd server:** nginx

**HTTPS:** yes

### Client configuration

**Android version:** 7.0.0

**Phone:** Oneplus 3

**ownCloud SMS app version:** 0.23.0

### Logs

```
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","Message":"An exception occurred while executing 'SELECT sms_address, sms_date, sms_msg, sms_type, sms_mailbox FROM oc_ocsms_smsdatas WHERE user_id = ? AND sms_date > ? ORDER BY sms_date LIMIT ?' with params [\"michi\", \"0\", \"500\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''500'' at line 1","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT sms_addr...', Array)\n#2 \/var\/www\/nextcloud\/lib\/private\/legacy\/db\/statementwrapper.php(74): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/nextcloud\/apps\/ocsms\/db\/smsmapper.php(156): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/nextcloud\/apps\/ocsms\/controller\/apicontroller.php(197): OCA\\OcSms\\Db\\SmsMapper->getMessages('michi', '0', '500')\n#5 [internal function]: OCA\\OcSms\\Controller\\ApiController->fetchMessages('0', '500')\n#6 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#7 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OcSms\\Controller\\ApiController), 'fetchMessages')\n#8 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OcSms\\Controller\\ApiController), 'fetchMessages')\n#9 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ApiController', 'fetchMessages', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/var\/www\/nextcloud\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/ocsms\/api...')\n#13 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":90}
```

**Comment by nerzhul** [comment]
It seems the nextcloud/owncloud frameworks has problem converting LIMIT to string instead of INT in MySQL (no problem with sqlite & pg)

**Comment by nerzhul** [comment]
Can you try this patch please ? https://github.com/nerzhul/ocsms/commit/292bd8b8140104fead7f8cba4ebd2d08b8776207

**Comment by nerzhul** [comment]
Fixed by recent @yneveu patch, thanks to him
